#ifndef PINOUT_H
#define PINOUT_H

#define CBT_TXD_PIN (GPIO_NUM_1)
#define CBT_RXD_PIN (GPIO_NUM_3)    
#define CBT_ADC_BATTERY_LEVEL_PIN (GPIO_NUM_2)

#define CBT_MOTOR_LEFT_PWM_PIN (GPIO_NUM_5)
#define CBT_MOTOR_LEFT_DIR_1_PIN (GPIO_NUM_19)
#define CBT_MOTOR_LEFT_DIR_2_PIN (GPIO_NUM_22)
#define CBT_MOTOR_RIGHT_PWM_PIN (GPIO_NUM_12)
#define CBT_MOTOR_RIGHT_DIR_1_PIN (GPIO_NUM_25)
#define CBT_MOTOR_RIGHT_DIR_2_PIN (GPIO_NUM_27)

#define CBT_ADC_WEAPON_CURRENT_PIN(GPIO_NUM_26)
#define CBT_WEAPON_PWM_PIN (GPIO_NUM_33)

#endif