#ifndef CMBT_PINOUT_H
#define CMBT_PINOUT_H

#define CMBT_TXD_PIN (GPIO_NUM_1)
#define CMBT_RXD_PIN (GPIO_NUM_3)    
#define CMBT_ADC_BATTERY_LEVEL_PIN (GPIO_NUM_2)

#define CMBT_MOTOR_LEFT_PWM_PIN (GPIO_NUM_15)
#define CMBT_MOTOR_LEFT_DIR_1_PIN (GPIO_NUM_19)
#define CMBT_MOTOR_LEFT_DIR_2_PIN (GPIO_NUM_22)
#define CMBT_MOTOR_RIGHT_PWM_PIN (GPIO_NUM_12)
#define CMBT_MOTOR_RIGHT_DIR_1_PIN (GPIO_NUM_25)
#define CMBT_MOTOR_RIGHT_DIR_2_PIN (GPIO_NUM_27)

#define CMBT_ADC_WEAPON_CURRENT_PIN(GPIO_NUM_26)
#define CMBT_WEAPON_PWM_PIN (GPIO_NUM_33)

#endif